### PR TITLE
Stop table cells from wrapping

### PR DESCRIPTION
**Pull request by keirog**
Before | After
---|---
Cells wrapping and looking not very nice | Cells not wrapping and looking super nice

 🐿 v2.11.0

### CODE REVIEW

**Comment by keirog** [comment]
@j-mes Any better? Guessing you were against the `td` so I’ve made it a content-type-specific HTML class

**Comment by keirog** [comment]
(Note: not actually put into use in this PR—that comes later)

**Comment by keirog** [comment]
Gonna merge this in but please do still critique!

**Comment by j-mes** [comment]
Your implementation of using classes to affect the `o-table` to `nowrap` for the whitespace is what I thought might be the best way, as in the future it can only affect those that have the no wrapping class :+1:

**Pull request merged**
